spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://101.132.167.102:3306/time-management?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: time-management
    password: 1qazXSW@

  session:
    store-type: none

#security:
#  basic:
#    enabled: false

server:
  port: 80
  session:
    timeout: 10 #秒

fez:
  security:
    browser:
      loginPage: /demo-signIn.html
      loginType: JSON
      signUpUrl: /demo-signUp.html
    code:
      image:
        width: 100
        height: 20
        length: 4
        expireIn: 100
        url: /user,/user/*
    social:
      qq:
        app-id:
        app-secret:
        providerId: callback.do
      weixin:
        app-id: wxd99431bbff8305a0
        app-secret: 60f78681d063590a469f1b297feff3c4
      filterProcessesUrl: /qqLogin
